const PDFDocument = require('pdfkit');

/**
 * generateQuizPDF
 * Streams a quiz results PDF to the Express response object.
 * @param {Object} payload - { quiz, questions, report, user }
 * @param {Object} res     - Express response stream
 */
const generateQuizPDF = (payload, res) => {
  return new Promise((resolve, reject) => {
    const { quiz, questions, report, user } = payload;
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    doc.on('error', reject);
    doc.pipe(res);

    // ── Header ──────────────────────────────────────────
    doc
      .fontSize(22)
      .fillColor('#1a1a2e')
      .text('MemoryMate AI', { align: 'center' })
      .fontSize(14)
      .fillColor('#4a4a6a')
      .text('Quiz Results Report', { align: 'center' })
      .moveDown(0.5);

    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor('#e0e0f0')
      .stroke()
      .moveDown(0.5);

    // ── Quiz Info ────────────────────────────────────────
    doc.fontSize(11).fillColor('#333');
    doc.text(`Student : ${user.name}`);
    doc.text(`Quiz    : ${quiz.title}`);
    if (quiz.topic) doc.text(`Topic   : ${quiz.topic}`);
    doc.text(`Type    : ${quiz.quiz_type}`);
    doc.text(`Date    : ${new Date(quiz.created_at).toLocaleDateString()}`);

    if (report) {
      doc.moveDown(0.3);
      doc
        .fontSize(13)
        .fillColor(report.score_percentage >= 70 ? '#1a7a4a' : '#c0392b')
        .text(
          `Score: ${report.score_percentage.toFixed(1)}%  (${report.correct_answers}/${report.total_questions} correct)`,
          { align: 'right' }
        );
    }

    doc
      .moveDown(0.5)
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor('#e0e0f0')
      .stroke()
      .moveDown(0.8);

    // ── Questions ────────────────────────────────────────
    questions.forEach((q, idx) => {
      const isCorrect = q.is_correct;

      doc
        .fontSize(11)
        .fillColor('#1a1a2e')
        .text(`Q${idx + 1}. ${q.question_text}`, { continued: false });

      // Options (MCQ)
      if (q.options && Array.isArray(q.options)) {
        q.options.forEach(opt => {
          doc.fontSize(10).fillColor('#555').text(`    • ${opt}`);
        });
      }

      doc.moveDown(0.2);

      doc
        .fontSize(10)
        .fillColor(isCorrect ? '#1a7a4a' : '#c0392b')
        .text(`  Your Answer : ${q.user_answer}`);

      if (!isCorrect) {
        doc
          .fillColor('#1a7a4a')
          .text(`  Correct     : ${q.correct_answer}`);
      }

      if (q.explanation) {
        doc
          .fillColor('#888')
          .text(`  Note        : ${q.explanation}`);
      }

      doc.moveDown(0.8);

      // Page break guard
      if (doc.y > 720) doc.addPage();
    });

    // ── Footer ───────────────────────────────────────────
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor('#e0e0f0')
      .stroke()
      .moveDown(0.4)
      .fontSize(9)
      .fillColor('#aaa')
      .text('Generated by MemoryMate AI', { align: 'center' });

    doc.end();
    doc.on('finish', resolve);
  });
};

module.exports = { generateQuizPDF };
